apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  labels:
    app: postgres
    component: database
data:
  database.name: "tesladb"
  database.host: "postgres"
  database.port: "5432"
