apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  labels:
    app: postgres
    component: database
type: Opaque
stringData:
  database.user: "postgres"
  database.password: "ferrari_postgres_pass_2024"
