apiVersion: v1
kind: Service
metadata:
  name: ferrari-backend
  labels:
    app: ferrari-backend
    component: api
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: ferrari-backend
---
apiVersion: v1
kind: Service
metadata:
  name: ferrari-backend-stable
  labels:
    app: ferrari-backend
    component: api
    service-type: stable
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: ferrari-backend
---
apiVersion: v1
kind: Service
metadata:
  name: ferrari-backend-canary
  labels:
    app: ferrari-backend
    component: api
    service-type: canary
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: ferrari-backend