apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: tesla-shop-dev

resources:
  - ../../base

images:
  - name: tesla-backend
    newName: ghcr.io/irfadkp/tesla-canary-app/backend
    newTag: "v1.0.15"
  - name: tesla-frontend
    newName: ghcr.io/irfadkp/tesla-canary-app/frontend
    newTag: "v1.0.15"

patches:
  - target:
      kind: Ingress
      name: tesla-ingress
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: tesla-shop.local