apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: tesla-shop-dev

resources:
  - ../../base

images:
  - name: tesla-backend
    newName: ghcr.io/irfadkp/tesla-canary-app/backend
    newTag: "1.0.0"
  - name: tesla-frontend
    newName: ghcr.io/irfadkp/tesla-canary-app/frontend
    newTag: "1.0.2"

patches:
  - target:
      kind: Ingress
      name: tesla-ingress
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: tesla-shop.local
  - target:
      kind: Rollout
      name: tesla-backend
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/readinessProbe
        value:
          httpGet:
            path: /health/nonexistent
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
          failureThreshold: 1