apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tesla-ingress
  labels:
    app: tesla
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  ingressClassName: traefik
  rules:
  - host: tesla-shop.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: tesla-frontend
            port:
              number: 80
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: tesla-backend
            port:
              number: 8080