apiVersion: v1
kind: Service
metadata:
  name: ferrari-frontend
  labels:
    app: ferrari-frontend
    component: ui
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: ferrari-frontend
