apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tesla-canary-app
  namespace: argocd-namespace
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/irfadkp/tesla-canary-app.git
    targetRevision: master
    path: gitops/overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: ferrari-shop-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  revisionHistoryLimit: 3
